# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: ^docs/
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.11
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: ['--ignore=F401', '--max-line-length=150']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
    -   id: mypy
-   repo: https://github.com/rubik/xenon
    rev: v0.9.3
    hooks:
    -   id: xenon
        args: ['--max-absolute=B', '--max-modules=B', '--max-average=A', '--exclude=tests/*']
-   repo: https://github.com/regebro/pyroma
    rev: "4.2"
    hooks:
    -   id: pyroma
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: ['--fail-under=80', '--verbose']
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args: ['--ignore=D203,D204,D212,D401,D413']
- repo: local
  hooks:
      - id: docs
        name: docs
        language: script
        pass_filenames: false
        entry: docs.sh
- repo: local
  hooks:
      - id: tests
        name: tests
        language: system
        pass_filenames: false
        entry: pytest
        fail_fast: true
- repo: local
  hooks:
      - id: coverage
        name: coverage
        language: script
        pass_filenames: false
        entry: coverage.sh
- repo: local
  hooks:
      - id: badges
        name: badges
        language: script
        pass_filenames: false
        entry: badges.sh
